# 텐서 조작하기(Tensor Manipulation) 1
## 넘파이로 텐서 만들기(벡터와 행렬 만들기)

### 1) 1D with Numpy

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t; ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t;  1
Shape of t:  (7,)


### 1-1) Numpy 기초 이해하기

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 
#통해 가져온다.

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[3:] = ', t[:2], t[3:]) # 시작번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2) 2D with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9. ], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [1]:
import torch

### 1) 1D with PyTorch

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim()) # rank. 즉, 차원
print(t.shape) # shape
print(t.size()) #shape

1
torch.Size([7])
torch.Size([7])


In [4]:
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1]) # 슬라이싱
print(t[:2], t[3:]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with PyTorch

In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.,],
                       [7., 8., 9.],
                       [10., 11., 12]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim()) # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [21]:
print(t[:,1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져오기
print(t[:,1].size()) # 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [36]:
print(t[:,:-1]) # 첫번째 차원을 전체 선택한 상황에서 두번쨰 차원에서는 맨 마지막에서
# 첫번째를 제외하고 다 가져온다.


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### 위의 내용을 설명하자면 ','은 차원을 구분하는 것이다.
#### 따라서 t[: 까지는 첫번째 차원을 모두 포함하고 ,:-1은 0부터 -1까지의 
#### 내용을 포함한다고 볼 수 있다.

### 3) 브로드캐스팅(Broadcasting)

In [37]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [38]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [39]:
# 2 x 1 Vector + 1 X 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### 4) 자주 사용되는 기능들
#### 1) 행렬 곱셉과 곰셈의 차이(Matrix Multiplication Vs. Multiplication)

In [41]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [42]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1*m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.  
[1]
[2]
==> [[1, 1],
     [2, 2]]

#### 2) 평균(Mean)

In [43]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [44]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [45]:
print(t.mean(dim=0))

tensor([2., 3.])


In [46]:
print(t.mean(dim=1))


tensor([1.5000, 3.5000])


In [47]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


#### 3) 덧셈(Sum)


In [48]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [49]:
print(t.sum()) # 단순 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행 단위로 연산 수행 or 연산 결과에서 행을 제거 
print(t.sum(dim=1)) # 열 단위로 연산 수행 or 연산 결과에서 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### 4) 최대(Max)와 아그맥스(ArgMax)

In [58]:
t = torch.FloatTensor([[6,2],[3,4]])
print(t)

tensor([[6., 2.],
        [3., 4.]])


In [59]:
print(t.max()) # Returns one value: max

tensor(6.)


In [60]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))


In [62]:
print('Max: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

Max:  tensor([6., 4.])
ArgMax:  tensor([0, 1])


In [63]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))
