# 텐서 조작하기(Tensor Manipulation) 1
## 넘파이로 텐서 만들기(벡터와 행렬 만들기)

### 1) 1D with Numpy

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t; ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t;  1
Shape of t:  (7,)


### 1-1) Numpy 기초 이해하기

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 
#통해 가져온다.

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[3:] = ', t[:2], t[3:]) # 시작번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2) 2D with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9. ], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [9]:
import torch

### 1) 1D with PyTorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim()) # rank. 즉, 차원
print(t.shape) # shape
print(t.size()) #shape

1
torch.Size([7])
torch.Size([7])


In [12]:
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1]) # 슬라이싱
print(t[:2], t[3:]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with PyTorch

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.,],
                       [7., 8., 9.],
                       [10., 11., 12]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim()) # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [15]:
print(t[:,1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져오기
print(t[:,1].size()) # 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [16]:
print(t[:,:-1]) # 첫번째 차원을 전체 선택한 상황에서 두번쨰 차원에서는 맨 마지막에서
# 첫번째를 제외하고 다 가져온다.


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### 위의 내용을 설명하자면 ','은 차원을 구분하는 것이다.
#### 따라서 t[: 까지는 첫번째 차원을 모두 포함하고 ,:-1은 0부터 -1까지의 
#### 내용을 포함한다고 볼 수 있다.

### 3) 브로드캐스팅(Broadcasting)

In [17]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [18]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [19]:
# 2 x 1 Vector + 1 X 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### 4) 자주 사용되는 기능들
#### 1) 행렬 곱셉과 곰셈의 차이(Matrix Multiplication Vs. Multiplication)

In [20]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [21]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1*m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.  
[1]
[2]
==> [[1, 1],
     [2, 2]]

#### 2) 평균(Mean)

In [22]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [23]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.mean(dim=0))

tensor([2., 3.])


In [25]:
print(t.mean(dim=1))


tensor([1.5000, 3.5000])


In [26]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


#### 3) 덧셈(Sum)


In [27]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum()) # 단순 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행 단위로 연산 수행 or 연산 결과에서 행을 제거 
print(t.sum(dim=1)) # 열 단위로 연산 수행 or 연산 결과에서 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### 4) 최대(Max)와 아그맥스(ArgMax)

In [29]:
t = torch.FloatTensor([[6,2],[3,4]])
print(t)

tensor([[6., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Returns one value: max

tensor(6.)


In [31]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))


In [32]:
print('Max: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

Max:  tensor([6., 4.])
ArgMax:  tensor([0, 1])


In [33]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 1]))


#### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경

In [34]:
t = np.array([[[0, 1, 2],
             [3, 4, 5]],
             [[6, 7, 8],
              [9, 10, 11]]])
tf = torch.FloatTensor(t)

In [35]:
print(tf.shape)

torch.Size([2, 2, 3])


현재 위 텐서의 크기는 (2, 2, 3)이다. 

#### 5-1) 3차원 텐서에서 2차원 텐서로 변경

In [36]:
print(tf.view([-1, 3])) # tf라는 텐서를 (?, 3)의 크기로 변경
print(tf.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


#### 5-2) 3차원 텐서의 크기 변경

In [38]:
print(tf.view([-1, 1, 3]))
print(tf.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### 6) 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [39]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [41]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [42]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [44]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### 8) 타입 캐스팅(Type Casting)

In [46]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [47]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [48]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [49]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [50]:
x = torch.FloatTensor([[1,2], [3, 4]])
y = torch.FloatTensor([[5,6], [7, 8]])

In [53]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [54]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [56]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [62]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [64]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [65]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [66]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [67]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [70]:
x= torch.FloatTensor([[1, 2], [3, 4]])

In [72]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [73]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
