# 03. Linear Regression(선형 회귀)
### 1. 기본 셋팅

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 같은 결과가 나오도록
# 랜덤 시드(random seed)를 준다.
torch.manual_seed(1)

### 2. 변수 선언

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### 3. 가중치와 편향의 초기화

In [8]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W=torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W)


tensor([0.], requires_grad=True)


In [11]:
b =torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### 4. 가설 세우기

In [12]:
hypothesis = x_train * W +b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 5. 비용 함수 선언하기

In [13]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 6. 경사 하강법 구현하기

In [14]:
optimizer = optim.SGD([W,b], lr=0.01)

In [15]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

### 7. 전체코드

In [17]:
#데이터 
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

In [19]:
nb_epochs = 1999 # 원하는 만큼 경사 하강법을 반복
for epoch in range(nb_epochs+1):
    # H(x) 계산
    hypothesis = x_train * W +b
    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} W: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W: 0.187 Cost: 0.080000
Epoch  100/1999 W: 1.746 Cost: 0.578072
Epoch  200/1999 W: 1.800 Cost: 0.454421
Epoch  300/1999 W: 1.843 Cost: 0.357217
Epoch  400/1999 W: 1.876 Cost: 0.280805
Epoch  500/1999 W: 1.903 Cost: 0.220738
Epoch  600/1999 W: 1.924 Cost: 0.173520
Epoch  700/1999 W: 1.940 Cost: 0.136403
Epoch  800/1999 W: 1.953 Cost: 0.107225
Epoch  900/1999 W: 1.963 Cost: 0.084289
Epoch 1000/1999 W: 1.971 Cost: 0.066259
Epoch 1100/1999 W: 1.977 Cost: 0.052085
Epoch 1200/1999 W: 1.982 Cost: 0.040944
Epoch 1300/1999 W: 1.986 Cost: 0.032185
Epoch 1400/1999 W: 1.989 Cost: 0.025301
Epoch 1500/1999 W: 1.991 Cost: 0.019889
Epoch 1600/1999 W: 1.993 Cost: 0.015634
Epoch 1700/1999 W: 1.995 Cost: 0.012290
Epoch 1800/1999 W: 1.996 Cost: 0.009661
Epoch 1900/1999 W: 1.997 Cost: 0.007595


## optimizer.zero_grad()가 필요한 이유

In [20]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    z = 2*w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


## torch.manual_seed()를 하는 이유

In [21]:
import torch

In [22]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [23]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [24]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])
